[build]
  publish = "generatorQR/static"
  command = "cd generatorQR && python manage.py collectstatic --noinput"

[build.environment]
  PYTHON_VERSION = "3.12"
  DJANGO_SETTINGS_MODULE = "generatorQR.settings"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/django/:splat"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/.netlify/functions/django/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"