# Generated by Django 5.0.6 on 2025-08-25 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('group_name', models.CharField(max_length=200, verbose_name='Nombre del Grupo')),
                ('whatsapp_number', models.CharField(max_length=20, verbose_name='Número de WhatsApp')),
                ('whatsapp_message', models.TextField(help_text='Mensaje que se enviará automáticamente al escanear el QR', verbose_name='Mensaje de WhatsApp')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('scan_count', models.PositiveIntegerField(default=0, verbose_name='Número de Escaneos')),
            ],
            options={
                'verbose_name': 'Código QR',
                'verbose_name_plural': 'Códigos QR',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='QR.qrcode')),
            ],
            options={
                'verbose_name': 'Escaneo de QR',
                'verbose_name_plural': 'Escaneos de QR',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
